server:
  port : 9099
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springboot
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
    show-sql: true


